import crypto from 'crypto';

// The encryption key must be stored in the ENCRYPTION_KEY environment variable.
// It must be exactly 32 bytes (64 hex characters) for AES-256.
// Generate one with: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
const ALGORITHM = 'aes-256-gcm';
const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY;
if (!ENCRYPTION_KEY || ENCRYPTION_KEY.length !== 64) {
    throw new Error(
        "ENCRYPTION_KEY environment variable is missing or invalid. " +
        "It must be exactly 64 hex characters (32 bytes). " +
        "Generate one with: node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
    );
}
const SECRET_KEY = ENCRYPTION_KEY;

/**
 * Encrypt sensitive data like Social Security Numbers for compliance.
 */
export function encryptString(text: string): string {
    const iv = crypto.randomBytes(16);
    const cipher = crypto.createCipheriv(ALGORITHM, Buffer.from(SECRET_KEY, 'hex'), iv);

    let encrypted = cipher.update(text, 'utf8', 'hex');
    encrypted += cipher.final('hex');

    const authTag = cipher.getAuthTag().toString('hex');

    // Return format: IV:EncryptedText:AuthTag
    return `${iv.toString('hex')}:${encrypted}:${authTag}`;
}

/**
 * Decrypt data matching the format generated by `encryptString`.
 */
export function decryptString(encryptedText: string): string {
    const [ivHex, encryptedHex, authTagHex] = encryptedText.split(':');

    if (!ivHex || !encryptedHex || !authTagHex) {
        throw new Error('Invalid encrypted text format');
    }

    const decipher = crypto.createDecipheriv(
        ALGORITHM,
        Buffer.from(SECRET_KEY, 'hex'),
        Buffer.from(ivHex, 'hex')
    );

    decipher.setAuthTag(Buffer.from(authTagHex, 'hex'));

    let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');

    return decrypted;
}
