import crypto from 'crypto';

// The encryption key should ideally be rotated and securely stored in environment variables.
// It must be exactly 32 bytes (64 hex characters) for AES-256
const ALGORITHM = 'aes-256-gcm';
const SECRET_KEY = process.env.ENCRYPTION_KEY || crypto.randomBytes(32).toString('hex');

/**
 * Encrypt sensitive data like Social Security Numbers for compliance.
 */
export function encryptString(text: string): string {
    const iv = crypto.randomBytes(16);
    const cipher = crypto.createCipheriv(ALGORITHM, Buffer.from(SECRET_KEY, 'hex'), iv);

    let encrypted = cipher.update(text, 'utf8', 'hex');
    encrypted += cipher.final('hex');

    const authTag = cipher.getAuthTag().toString('hex');

    // Return format: IV:EncryptedText:AuthTag
    return `${iv.toString('hex')}:${encrypted}:${authTag}`;
}

/**
 * Decrypt data matching the format generated by `encryptString`.
 */
export function decryptString(encryptedText: string): string {
    const [ivHex, encryptedHex, authTagHex] = encryptedText.split(':');

    if (!ivHex || !encryptedHex || !authTagHex) {
        throw new Error('Invalid encrypted text format');
    }

    const decipher = crypto.createDecipheriv(
        ALGORITHM,
        Buffer.from(SECRET_KEY, 'hex'),
        Buffer.from(ivHex, 'hex')
    );

    decipher.setAuthTag(Buffer.from(authTagHex, 'hex'));

    let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');

    return decrypted;
}
