export const SUBSCRIPTION_PLANS = [
  {
    id: "solo",
    name: "SOLO / DÉMARRAGE",
    price: 25000,
    currency: "FCFA",
    period: "mois",
    description: "Cible : Le médecin qui consulte seul (souvent dans un cabinet partagé).",
    features: [
      { text: "Agenda & Dossier Spécialisé", included: true },
      { text: "SMS Rappels : 150/mois inclus", included: true },
      { text: "Ordonnances & Certificats digitaux", included: true },
      { text: "Support par Chat (WhatsApp)", included: true },
      { text: "Accès Secrétariat", included: false },
      { text: "Téléconsultation Vidéo HD", included: false },
    ],
    isPopular: false,
    cta: "Démarrer Solo",
  },
  {
    id: "pro",
    name: "CABINET PRO",
    price: 50000,
    currency: "FCFA",
    period: "mois",
    description: "Le choix standard pour les cabinets avec secrétaire.",
    features: [
      { text: "Tout le pack Solo", included: true },
      { text: "Accès Secrétariat illimité", included: true },
      { text: "500 SMS de rappel inclus/mois", included: true },
      { text: "Téléconsultation Vidéo HD", included: true },
      { text: "Suivi des encaissements (Wave/OM)", included: true },
      { text: "Statistiques d'activité & Finance", included: true },
    ],
    isPopular: true,
    cta: "Choisir Pro",
  },
  {
    id: "clinique",
    name: "CLINIQUE",
    price: 95000,
    currency: "FCFA",
    period: "mois",
    description: "Puissance maximale pour cliniques multi-praticiens.",
    features: [
      { text: "Médecins illimités", included: true },
      { text: "2000 SMS de rappel inclus/mois", included: true },
      { text: "Assistant IA (Comptes-rendus auto)", included: true },
      { text: "Gestion de Stock & Pharmacie", included: true },
      { text: "Support Prioritaire 24h/24 & 7j/7", included: true },
      { text: "Développement sur mesure (API)", included: true },
    ],
    isPopular: false,
    cta: "Contacter Ventes",
  }
];
